apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: devops-integration
spec:
  selector:
    matchLabels:
      app: devops-integration
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: devops-integration
    spec:
      containers:
        - name: devops-integration
          image: ivakis/devops-integration:2.0.0-SNAPSHOT # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: devops-integration
spec:
  selector:
    app: devops-integration
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.