version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000" # agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    user: root

volumes:
  jenkins_home:

#use the generated password in the container logs to enter on localhost:8080
#craate admin user: admin:admin
#dashboard -> manage jenkins -> tools configuration -> add maven 3_5_0 from apache automated
# new element: devops-automation (pipeline)
# give gitHubUrl: https://github.com/sublime-exp/devops-automation
# GitHub hook trigger for GITScm polling

#script:
#pipeline {
#    agent any
#    tools {
#        maven "maven_3_5_0"
#    },
#    stages{
#       stage('Build Maven') {
#            steps {
#              <generated snippet from the pipeline syntax option for the 'check version control' snippet>
#              <give the url to the repo and change the branch to 'main'>
#              checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sublime-exp/devops-automation']])
#              sh "mvn clean install"
#            }
#    }
#}
#

